导入库

In [41]:
import pandas as pd
import numpy as np
import glob
import os
import re

In [27]:
test=pd.read_csv(r'C:\Users\Ziao\Desktop\n2c2\df_fun1.csv')

In [3]:
df_label_I=pd.read_csv(r'C:\Users\Ziao\Desktop\n2c2\df_result.csv')
df_label_I.columns = ['Noteid','T','Position','Start','End','Word','Label']
df_label_I

     Noteid    T       Position  Start   End        Word Label
0    101-03   T6    Disposition   1719  1726     nitrate     I
1    101-03   T6    Disposition   1712  1718      acting     I
2    106-01   T9  NoDisposition   2223  2233  medication     I
3    106-02   T4  NoDisposition   1353  1355          LA     I
4    108-02  T23  NoDisposition   1559  1565      SODIUM     I
..      ...  ...            ...    ...   ...         ...   ...
934  396-03  T25  NoDisposition   1230  1239   Succinate     I
935  396-03  T28  NoDisposition   1576  1583     Release     I
936  396-03  T28  NoDisposition   1566  1575   Sustained     I
937  398-01   T6  NoDisposition    495   499        ACID     I
938  399-02  T33  NoDisposition   3598  3606    vitamins     I

[939 rows x 7 columns]

In [4]:
df_label_B=pd.read_csv(r'C:\Users\Ziao\Desktop\n2c2\df2.csv')
df_label_B.columns = ['Noteid','T','Position','Start','End','Word','Label']
df_label_B

      Noteid    T       Position  Start   End                 Word Label
0     101-01   T2  NoDisposition    703   710              Lipitor     B
1     101-01   T3  NoDisposition   2090  2099            Synthroid     B
2     101-02   T2  NoDisposition    830   838             atenolol     B
3     101-02   T3  NoDisposition   1389  1408  hydrochlorothiazide     B
4     101-02   T4  NoDisposition   1414  1422             atenolol     B
...      ...  ...            ...    ...   ...                  ...   ...
6000  399-02  T32  NoDisposition   3588  3594               folate     B
6001  399-02  T33  NoDisposition   3596  3597                    B     B
6002  399-02  T34  NoDisposition   3616  3623              Allegra     B
6003  399-02  T35    Disposition   5136  5142               Elavil     B
6004  399-02  T36  NoDisposition   5211  5217               Elavil     B

[6005 rows x 7 columns]

# 单词处理

In [7]:
test

,NotesId,SentenceId,Sentence,Start,End,Section,PrevSentId,NextSentId
0,101-01,101-01_1,\n\n\nRecord date: 2079-05-12\n\n\n\n\n\nMERCY...,0,201,No Section,NaN,101-01_2
1,101-01,101-01_2,She has been in Rhode Island for \nsix months.,202,248,No Section,101-01_1,101-01_3
2,101-01,101-01_3,Her complaint is that she has heaviness in th...,249,303,No Section,101-01_2,101-01_4
3,101-01,101-01_4,She \ndoes not have any palpitations.,304,341,No Section,101-01_3,101-01_5
4,101-01,101-01_5,She does not note that this is \nassociated w...,342,400,No Section,101-01_4,101-01_6
5,101-01,101-01_6,She does have diaphoresis associated with it.,401,447,No Section,101-01_5,101-01_7
6,101-01,101-01_7,\nShe does not have any shortness of breath.,448,492,No Section,101-01_6,101-01_8
7,101-01,101-01_8,This heaviness has been in \nher chest on and...,493,566,No Section,101-01_7,101-01_9
8,101-01,101-01_9,She is quite concerned.,567,591,No Section,101-01_8,101-01_10
9,101-01,101-01_10,\n\nShe has a history of hypothyroidism and hy...,591,646,No Section,101-01_9,101-01_11
10,101-01,101-01_11,She also has \nhyperlipidemia and is being tr...,647,711,No Section,101-01_10,101-01_12
11,101-01,101-01_12,Her health \nmaintenance has been in order.,712,755,No Section,101-01_11,101-01_13
12,101-01,101-01_13,She has just had a hysterectomy.,756,789,No Section,101-01_12,101-01_14
13,101-01,101-01_14,She \nneeds to have a follow-up mammogram done.,790,837,No Section,101-01_13,101-01_15
14,101-01,101-01_15,"However, today I am most \nconcerned about he...",838,901,No Section,101-01_14,101-01_16
15,101-01,101-01_16,\n\n,0,2,No Section,101-01_15,101-01_17
16,101-01,101-01_17,": Her blood pressure is 130/80, respiratory r...",923,996,PHYSICAL EXAMINATION,101-01_16,101-01_18
17,101-01,101-01_18,Neck is supple.,997,1013,PHYSICAL EXAMINATION,101-01_17,101-01_19
18,101-01,101-01_19,There is no lymphadenopathy.,1014,1043,PHYSICAL EXAMINATION,101-01_18,101-01_20
19,101-01,101-01_20,\nChest is clear to both percussion and auscu...,1044,1097,PHYSICAL EXAMINATION,101-01_19,101-01_21
20,101-01,101-01_21,Cardiac exam is \nregularly regular with no m...,1098,1167,PHYSICAL EXAMINATION,101-01_20,101-01_22
21,101-01,101-01_22,Abdomen is soft and \nnontender.,1168,1200,PHYSICAL EXAMINATION,101-01_21,101-01_23
22,101-01,101-01_23,There is no hepatosplenomegaly.,1201,1233,PHYSICAL EXAMINATION,101-01_22,101-01_24
23,101-01,101-01_24,"Extremities are clear of \ncyanosis, clubbing...",1234,1290,PHYSICAL EXAMINATION,101-01_23,101-01_25
24,101-01,101-01_25,\n\n,0,2,PHYSICAL EXAMINATION,101-01_24,101-01_26
25,101-01,101-01_26,": Her sodium is 145, electrolytes are all oth...",1307,1382,LABORATORY DATA,101-01_25,101-01_27
26,101-01,101-01_27,TSH is 2.0.,1383,1395,LABORATORY DATA,101-01_26,101-01_28
27,101-01,101-01_28,LFTs are pending at this time.,1396,1427,LABORATORY DATA,101-01_27,101-01_29
28,101-01,101-01_29,"We \nsent her for an electrocardiogram, which...",1428,1537,LABORATORY DATA,101-01_28,101-01_30
29,101-01,101-01_30,We also sent her for an exercise \ntolerance ...,1538,1718,LABORATORY DATA,101-01_29,101-01_31
30,101-01,101-01_31,She had no evidence of ischemia.,1719,1752,LABORATORY DATA,101-01_30,101-01_32
31,101-01,101-01_32,\n\n,0,2,LABORATORY DATA,101-01_31,101-01_33
32,101-01,101-01_33,:\n1.,1773,1777,ASSESSMENT AND PLAN,101-01_32,101-01_34
33,101-01,101-01_34,\tChest heaviness.,1777,1794,ASSESSMENT AND PLAN,101-01_33,101-01_35
34,101-01,101-01_35,I am not sure what is causing this.,1795,1831,ASSESSMENT AND PLAN,101-01_34,101-01_36
35,101-01,101-01_36,She may have a \nprimary pulmonary problem.,1832,1875,ASSESSMENT AND PLAN,101-01_35,101-01_37
36,101-01,101-01_37,She will be following up with us in one \nweek.,1876,1923,ASSESSMENT AND PLAN,101-01_36,101-01_38
37,101-01,101-01_38,It is heartening to see that she does not hav...,1924,2009,ASSESSMENT AND PLAN,101-01_37,101-01_39
38,101-01,101-01_39,\n2.,2009,2012,ASSESSMENT AND PLAN,101-01_38,101-01_40
39,101-01,101-01_40,"\tHypothyroidism, well controlled at the prese...",2012,2065,ASSESSMENT AND PLAN,101-01_39,101-01_41
40,101-01,101-01_41,Continue same \ndose of Synthroid.,2066,2100,ASSESSMENT AND PLAN,101-01_40,101-01_42
41,101-01,101-01_42,\n3.,2100,2103,ASSESSMENT AND PLAN,101-01_41,101-01_43
42,101-01,101-01_43,"\tHypertension, well controlled presently.",2103,2144,ASSESSMENT AND PLAN,101-01_42,101-01_44
43,101-01,101-01_44,\n4.,2144,2147,ASSESSMENT AND PLAN,101-01_43,101-01_45
44,101-01,101-01_45,\tHyperlipidemia.,2147,2163,ASSESSMENT AND PLAN,101-01_44,101-01_46
45,101-01,101-01_46,We will recheck this on her next visit.,2164,2204,ASSESSMENT AND PLAN,101-01_45,101-01_47
46,101-01,101-01_47,"\n\n\n\nRE: Russell, Donna\nMRN #: 10418061\...",2204,2319,ASSESSMENT AND PLAN,101-01_46,101-01_48
47,101-01,101-01_48,\n\n\n\n_______________________________\nQuinn...,2319,2452,ASSESSMENT AND PLAN,101-01_47,NaN

In [28]:
test.loc[1]['Sentence'].split()

['She', 'has', 'been', 'in', 'Rhode', 'Island', 'for', 'six', 'months.']

切分成单个单词

In [43]:
re.findall(r"[\w']+|[.,!?;]", test.loc[1]['Sentence'])

['She', 'has', 'been', 'in', 'Rhode', 'Island', 'for', 'six', 'months', '.']

In [48]:

list=[]
for j in range(0,len(test)):
  for i in re.findall(r"[\w']+|[.,!?;]", test.loc[j]['Sentence']):
    m=test.loc[j]['Sentence'].find(i)+test.loc[j]['Start']
    list.append(pd.DataFrame({'Noteid':test.loc[j]['NotesId'],'Sentenceid':test.loc[j]['SentenceId'],'Word':i,'Start':m,'End':m+len(i)}, index=[0]))
    df3 = pd.concat(list, axis=0, ignore_index=True)
    print(i)

Record
date
2079
05
12
MERCY
CARE
CENTER
Mercy
Internal
Medicine
Associates
8
Newburgh
Street
Terrell
,
AR
72985
Russell
,
Donna
10418061
05
12
79
Ms
.
Russell
comes
in
for
further
evaluation
.
She
has
been
in
Rhode
Island
for
six
months
.
Her
complaint
is
that
she
has
heaviness
in
the
chest
.
She
does
not
have
any
palpitations
.
She
does
not
note
that
this
is
associated
with
exertion
.
She
does
have
diaphoresis
associated
with
it
.
She
does
not
have
any
shortness
of
breath
.
This
heaviness
has
been
in
her
chest
on
and
off
for
the
last
six
weeks
.
She
is
quite
concerned
.
She
has
a
history
of
hypothyroidism
and
hypertension
.
She
also
has
hyperlipidemia
and
is
being
treated
with
Lipitor
.
Her
health
maintenance
has
been
in
order
.
She
has
just
had
a
hysterectomy
.
She
needs
to
have
a
follow
up
mammogram
done
.
However
,
today
I
am
most
concerned
about
her
chest
heaviness
.
Her
blood
pressure
is
130
80
,
respiratory
rate
is
20
and
pulse
is
68
.
Neck
is
supple
.
There
is
no
lymphadenopathy
.
Chest
is
clear
to
both
percussion
and
auscultation
.
Cardiac
exam
is
regularly
regular
with
no
murmurs
,
gallops
or
rubs
.
Abdomen
is
soft
and
nontender
.
There
is
no
hepatosplenomegaly
.
Extremities
are
clear
of
cyanosis
,
clubbing
and
edema
.
Her
sodium
is
145
,
electrolytes
are
all
otherwise
within
normal
limits
.
TSH
is
2
.
0
.
LFTs
are
pending
at
this
time
.
We
sent
her
for
an
electrocardiogram
,
which
showed
normal
sinus
rhythm
with
nonspecific
ST
T
wave
changes
.
We
also
sent
her
for
an
exercise
tolerance
test
with
preliminary
reports
showing
that
she
went
to
a
maximum
heart
rate
of
108
,
she
was
on
the
protocol
for
6
minutes
50
seconds
.
She
had
no
evidence
of
ischemia
.
1
.
Chest
heaviness
.
I
am
not
sure
what
is
causing
this
.
She
may
have
a
primary
pulmonary
problem
.
She
will
be
following
up
with
us
in
one
week
.
It
is
heartening
to
see
that
she
does
not
have
an
abnormal
exercise
tolerance
test
.
2
.
Hypothyroidism
,
well
controlled
at
the
present
time
.
Continue
same
dose
of
Synthroid
.
3
.
Hypertension
,
well
controlled
presently
.
4
.
Hyperlipidemia
.
We
will
recheck
this
on
her
next
visit
.
RE
Russell
,
Donna
MRN
10418061
May
12
,
2079
Page
2
We
will
also
need
to
schedule
a
follow
up
mammogram
.
_______________________________
Quinn
Rutledge
,
M
.
D
.
QR
QR5
957307
.
doc
DD
05
25
2079
DT
05
27
2079
DV
05
12
2079

In [ ]:

# list=[]
# for j in range(0,len(test)):
#   for i in test.loc[j]['Sentence'].split():
#     m=test.loc[j]['Sentence'].find(i)+test.loc[j]['Start']
#     list.append(pd.DataFrame({'Noteid':test.loc[j]['NotesId'],'Sentenceid':test.loc[j]['SentenceId'],'Word':i,'Start':m,'End':m+len(i)}, index=[0]))
#     df3 = pd.concat(list, axis=0, ignore_index=True)
#     print(i)

In [49]:
df3
# df3.columns = ['Noteid','Sentenceid','Word','Start','End','Word']

     Noteid Sentenceid    Word  Start   End
0    101-01   101-01_1  Record      3     9
1    101-01   101-01_1    date     10    14
2    101-01   101-01_1    2079     16    20
3    101-01   101-01_1      05     21    23
4    101-01   101-01_1      12     24    26
..      ...        ...     ...    ...   ...
454  101-01  101-01_48    2079   2407  2411
455  101-01  101-01_48      DV   2428  2430
456  101-01  101-01_48      05   2401  2403
457  101-01  101-01_48      12   2436  2438
458  101-01  101-01_48    2079   2407  2411

[459 rows x 5 columns]

In [50]:
df3[df3['Word'] == 'Lipitor']

     Noteid Sentenceid     Word  Start  End
130  101-01  101-01_11  Lipitor    703  710

In [52]:
df_result = pd.merge(df3,df_label_B,on=['Noteid','Word','Start','End'],how='left')
df_result

     Noteid Sentenceid    Word  Start   End    T Position Label
0    101-01   101-01_1  Record      3     9  NaN      NaN   NaN
1    101-01   101-01_1    date     10    14  NaN      NaN   NaN
2    101-01   101-01_1    2079     16    20  NaN      NaN   NaN
3    101-01   101-01_1      05     21    23  NaN      NaN   NaN
4    101-01   101-01_1      12     24    26  NaN      NaN   NaN
..      ...        ...     ...    ...   ...  ...      ...   ...
454  101-01  101-01_48    2079   2407  2411  NaN      NaN   NaN
455  101-01  101-01_48      DV   2428  2430  NaN      NaN   NaN
456  101-01  101-01_48      05   2401  2403  NaN      NaN   NaN
457  101-01  101-01_48      12   2436  2438  NaN      NaN   NaN
458  101-01  101-01_48    2079   2407  2411  NaN      NaN   NaN

[459 rows x 8 columns]

In [54]:
df_result['Label'].value_counts()

B    2
Name: Label, dtype: int64

以下和任务无关

In [ ]:
str2 ='''0

1
2
3
4
5
MERCY CARE CENTER
Mercy Internal Medicine Associates
8 Newburgh Street
Terrell, AR 72985'''

In [ ]:
str2.find('1')
# 会计算换行符\

3

In [35]:
str = '''


Record date: 2079-05-12





MERCY CARE CENTER
Mercy Internal Medicine Associates
8 Newburgh Street
Terrell, AR 72985

Russell, Donna
10418061
05/12/79


Ms. Russell comes in for further evaluation.  She has been in Rhode Island for 
six months.  Her complaint is that she has heaviness in the chest.  She 
does not have any palpitations.  She does not note that this is 
associated with exertion.  She does have diaphoresis associated with it.  
She does not have any shortness of breath.  This heaviness has been in 
her chest on and off for the last six weeks.  She is quite concerned.

She has a history of hypothyroidism and hypertension.  She also has 
hyperlipidemia and is being treated with Lipitor.  Her health 
maintenance has been in order.  She has just had a hysterectomy.  She 
needs to have a follow-up mammogram done.  However, today I am most 
concerned about her chest heaviness.

PHYSICAL EXAMINATION:  Her blood pressure is 130/80, respiratory rate is 
20 and pulse is 68.  Neck is supple.  There is no lymphadenopathy.  
Chest is clear to both percussion and auscultation.  Cardiac exam is 
regularly regular with no murmurs, gallops or rubs.  Abdomen is soft and 
nontender.  There is no hepatosplenomegaly.  Extremities are clear of 
cyanosis, clubbing and edema.

LABORATORY DATA:  Her sodium is 145, electrolytes are all otherwise 
within normal limits.  TSH is 2.0.  LFTs are pending at this time.  We 
sent her for an electrocardiogram, which showed normal sinus rhythm with 
nonspecific ST-T wave changes.  We also sent her for an exercise 
tolerance test with preliminary reports showing that she went to a 
maximum heart rate of 108, she was on the protocol for 6 minutes 50 
seconds.  She had no evidence of ischemia.

ASSESSMENT AND PLAN:
1.	Chest heaviness.  I am not sure what is causing this.  She may have a 
primary pulmonary problem.  She will be following up with us in one 
week.  It is heartening to see that she does not have an abnormal 
exercise tolerance test.
2.	Hypothyroidism, well controlled at the present time.  Continue same 
dose of Synthroid.
3.	Hypertension, well controlled presently.
4.	Hyperlipidemia.  We will recheck this on her next visit.



RE:  Russell, Donna
MRN #:  10418061
May 12, 2079
Page 2


We will also need to schedule a follow-up mammogram.



_______________________________
Quinn Rutledge, M.D.

QR/QR5
957307.doc
DD:  
05/25/2079
DT:  05/27/2079
DV:  05/12/2079








'''

In [38]:
str.find('She')

203

In [ ]:
data = {'noteid':['278-01','278-02','278-03','278-04','278-05'],
       '0':['T1','T2','T3','T4','T5'],
       '1':['Disposition1','Disposition2','NoDisposition3','Disposition4','NoDisposition5',],
        '2':[230,1,520,32,46],
        '3':[232,10,523,39,58],
        '4':['NO','I','YES','You','ok'],
        '5':[np.nan,'am',np.nan,'are','I'],
        '6':[np.nan,'good',np.nan,np.nan,'like'],
        '7':[np.nan,np.nan,np.nan,np.nan,'it'],
        '8':[np.nan,np.nan,np.nan,np.nan,np.nan],
        '9':[np.nan,np.nan,np.nan,np.nan,np.nan],
        '10':[np.nan,np.nan,np.nan,np.nan,np.nan],
        '11':[np.nan,np.nan,np.nan,np.nan,np.nan],
        '12':[np.nan,np.nan,np.nan,np.nan,np.nan],
        '13':[np.nan,np.nan,np.nan,np.nan,np.nan],
        '14':[np.nan,np.nan,np.nan,np.nan,np.nan],
        '15':[np.nan,np.nan,np.nan,np.nan,np.nan]
        }
df2 = pd.DataFrame(data)